# GitHub Actions workflow that handles the automation process when a tool is approved. This workflow is triggered when a tool submission is approved and handles the necessary updates to the repository, such as updating the tools list and documentation.
name: Process Tools

on:
  issues:
    types: ["labeled"]

concurrency: add_tool

jobs:
  update-tools-json:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'approved'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Execute process_tools_submission.py
        id: python_script
        env:
          GITHUB_EVENT_PATH: ${{ github.event_path }}
        run: python .github/scripts/process_tools_submission.py $GITHUB_EVENT_PATH

      - name: Commit Updated tools.json
        if: success()
        run: |
          git config --local user.email ${{ steps.python_script.outputs.commit_email }}
          git config --local user.name ${{ steps.python_script.outputs.commit_username }}
          git add .github/scripts/tools.json
          git diff-index --quiet HEAD || (git commit -a -m "${{ steps.python_script.outputs.commit_message }}" --allow-empty)

      - name: Push Changes
        if: success()
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: addingScripts

      - name: Auto Close Issue
        run: gh issue close --comment "Your tool submission was accepted and added to the tools list. Auto-closing issue." ${{ github.event.issue.number }}
        if: success()
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Problem With Action
        run: gh issue comment ${{ github.event.issue.number }} --body "There was an error with our GitHub action. Error - ${{ steps.python_script.outputs.error_message }}"
        if: failure()
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
